[package]
authors = ["Jauhien Piatlicki <jauhien@gentoo.org>"]
build = "build.rs"
name = "iron_llvm"
version = "0.0.1"

[build-dependencies]
cmake = "0.1.18"

[dependencies]
libc = "0.2.17"

[dependencies.llvm-sys]
git = "https://github.com/RReverser/llvm-sys.rs.git"
